apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shiny-spoons-s1
  labels:
    app: shiny-spoons-s1
    release: c756
spec:
  namespaceSelector:
    matchNames:
      - c756ns
  selector:
    matchLabels:
      app: shiny-spoons-s1
  endpoints:
    - port: http
      path: /metrics
