apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shiny-spoons-s2
  labels:
    app: shiny-spoons-s2
    release: c756
spec:
  namespaceSelector:
    matchNames:
      - c756ns
  selector:
    matchLabels:
      app: shiny-spoons-s2
  endpoints:
    - port: http
      path: /metrics
